export const SEARCH_BY_INGREDIENT_SUCCESS = "SEARCH_BY_INGREDIENT_SUCCESS";
export const SEARCH_BY_INGREDIENT_HEADER_SUCCESS = "SEARCH_BY_INGREDIENT_HEADER_SUCCESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT"